### ISSUE TITLE
Still unhappy with the fonts. Suggest serif font on titles, san serif on body text.

### ISSUE THREAD

**Issue by austinkocher** [LawandSpace/Law-Space-Website#4]

**Comment by Riwajchalise** [comment]
I have changed it accordingly let me know if you like it now.

**Comment by austinkocher** [comment]
I'll check now, thanks.

**Comment by Riwajchalise** [comment]
Sure it might take couple pf minutes to reflect on site

**Comment by austinkocher** [comment]
FYI: I don't see any change yet (>1hr).

**Comment by Riwajchalise** [comment]
Could possibly be due to cache, or it was hard to notice the difference.
Can you please send the screenshot of the fonts on title and content?

**Comment by austinkocher** [comment]
You're right! Caching issue. My fault.
